version: '3'

networks:
    overlay:

volumes:
    springSecurity_pg_data:

services:
    database:
        image: postgres:15
        container_name: springSecurity-postgres
        restart: unless-stopped
        environment:
            - POSTGRES_DB=testSecurity
            - POSTGRES_USER=springSecurityModuleTest
            - POSTGRES_PASSWORD=test
        ports:
            - '5432:5432'
        networks:
            - overlay
        volumes:
            - springSecurity_pg_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: springSecurity_pgadmin
        restart: unless-stopped
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - '15432:80'
        networks:
            - overlay
