spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/testSecurity
        username: springSecurityModuleTest
        password: test
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        datasource.platform: org.hibernate.dialect.PostgreSQLDialect
security:
    user:
        name: main_user
        password: pass365
        role: main_role
    jwt:
        header: Authorization
        secretKey: $2a$10$WcGBF8iWgL4yZ.gYOPQ37O5FvCZyIVrNVEUq8oLtP8JzNaVR2hiLy
        lifetimeBySeconds: 300
